# Data Preprocess 3

This journal explains how to filter the recycling plants candidate locations according to Energy Justice metrics, leveraging [EJScreen: Environmental Justice Screening and Mapping Tool](https://www.epa.gov/ejscreen), more specifically, we will be using [EJScreen Report API](https://ejscreen.epa.gov/mapper/ejscreenapi.html).

## 0. Load necessary libraries

In [1]:
import numpy as np
import pandas as pd
import os,sys
import matplotlib.pyplot as plt
from pathlib import Path

import requests # to get api data

## 1. Load the file to filter and add FIPS codes

EJScreen API needs FIPS codes to access the EJ reports. So the first step is to load the file we want to use, in our case 'RELOG_import_data/CandidateLocations_CA_CASE0'.

In [4]:
candidates_raw = pd.read_csv('RELOG_import_data/CandidateLocations_CA_CASE0.csv')
candidates_lat_long = candidates_raw.drop(['name', 'area cost factor'], axis=1, inplace= False)

In [5]:
candidates_lat_long

     latitude (deg)  longitude (deg)
0         40.694300       -73.924900
1         34.113900      -118.406800
2         41.837300       -87.686200
3         25.783900       -80.210200
4         32.793600       -96.766200
..              ...              ...
151       39.613044      -119.251397
152       39.528106      -119.490916
153       44.095657      -121.305861
154       39.199730      -119.735956
155       39.713622       -82.544377

[156 rows x 2 columns]

In [6]:
fips_county_codes = []
fips_state_codes = []

In [7]:
# Code from https://gis.stackexchange.com/questions/294641/python-code-for-transforming-lat-long-into-fips-codes
import requests
import urllib

#Encode parameters 
for lat, lon in candidates_lat_long.itertuples(index=False):
    params = urllib.parse.urlencode({'latitude': lat, 'longitude':lon, 'format':'json'})
    #Contruct request URL
    url = 'https://geo.fcc.gov/api/census/block/find?' + params

    #Get response from API
    response = requests.get(url)

    #Parse json in response
    data = response.json()
    fips_county_codes.append(data['County']['FIPS'])
    fips_state_codes.append(data['State']['FIPS'])
    #Print FIPS code

In [8]:
candidates_lat_long['fips_county'] = fips_county_codes
candidates_lat_long['fips_state'] = fips_state_codes

Let's reshape the dataframe to have the names back and all the  EJ indices in the dataframe related to the fips codes.

In [9]:
ej_candidates = candidates_lat_long.copy()

In [10]:
ej_candidates['name'] = candidates_raw['name']

Now, I am going to query a random fips code to get the column names.

In [11]:
ej_query = requests.get(f'https://ejscreen.epa.gov/mapper/ejscreenRESTbroker.aspx?namestr=Pickens County&geometry=&distance=&unit=9035&areatype=county&areaid=35003&f=pjson')
ej_query_keys = [keys for keys in ej_query.json().keys()]

In [20]:
ej_candidates

,latitude (deg),longitude (deg),fips_county,fips_state,name,RAW_D_MINOR,RAW_D_INCOME,RAW_D_LESSHS,RAW_D_LING,RAW_D_UNDER5,...,statLayerCount,statLayerZeroPopCount,weightLayerCount,timeSeconds,distance,unit,areaid,areatype,statlevel,inputAreaMiles
0,40.694300,-73.924900,36047,36,"New York, , New York",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34.113900,-118.406800,06037,06,"Los Angeles, Los Angeles County, California",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41.837300,-87.686200,17031,17,"Chicago, Cook County, Illinois",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25.783900,-80.210200,12086,12,"Miami, Miami-Dade County, Florida",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,32.793600,-96.766200,48113,48,"Dallas, Dallas County, Texas",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,39.613044,-119.251397,32019,32,"ABTC-Fernley, Lyon County, Nevada",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,39.528106,-119.490916,32029,32,"LiNiCoComstock-McCarran, Storey County, Nevada",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,44.095657,-121.305861,41017,41,"OnTo Tech-Bend, Deschutes County, Oregon",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,39.199730,-119.735956,32510,32,"Redwood Mat-Carson City, , Nevada",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,39.713622,-82.544377,39045,39,"Retriev-Lancaster, Fairfield County, Ohio",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
ej_candidates[ej_query_keys] = np.nan

/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan
/var/folders/w2/85_h_nyn0mlbxf81x3k9n53xh90n_1/T/ipykernel_77813/2673602796.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ej_candidates[ej_query_keys] = np.nan

In [29]:
ej_query_values = [value for value in ej_query.json().values()]

In [30]:
ej_query_values

['17%',
 '53%',
 '7%',
 '2%',
 '2%',
 '42%',
 '5%',
 '35%',
 '0.14',
 '0.0102',
 '10',
 '0.1',
 '1.2',
 'N/A',
 '0.0074',
 '0.056',
 '0.011',
 '56.4',
 '4.57',
 '0.0068',
 '63%',
 '39%',
 '14%',
 '5%',
 '6%',
 '17%',
 '7%',
 '51%',
 '0.18',
 '0.198',
 '20',
 '0.23',
 '510',
 '3.5',
 '0.14',
 '0.24',
 '0.81',
 '56',
 '5.54',
 '3.3',
 '  4',
 ' 70',
 ' 37',
 ' 50',
 ' 28',
 ' 94',
 ' 54',
 ' 25',
 ' 56',
 '  0',
 '  0',
 '  0',
 '  2',
 'N/A',
 '  3',
 ' 29',
 '  4',
 ' 54',
 ' 18',
 ' 24',
 ' 43',
 '  0',
 '  0',
 '  0',
 '  0',
 'N/A',
 '  4',
 ' 19',
 '  4',
 ' 42',
 ' 16',
 ' 27',
 '40%',
 '30%',
 '12%',
 '5%',
 '6%',
 '16%',
 '5%',
 '35%',
 '0.27',
 '0.294',
 '28',
 '0.36',
 '760',
 '12',
 '0.13',
 '0.77',
 '2.2',
 '42.5',
 '8.67',
 '3.9',
 '35',
 '83',
 '46',
 '63',
 '23',
 '96',
 '61',
 '59',
 '41',
 '0',
 '2',
 '1',
 '2',
 'N/A',
 '2',
 '7',
 '1',
 '95',
 '0',
 '0',
 '55',
 '0',
 '2',
 '1',
 '3',
 'N/A',
 '4',
 '13',
 '2',
 '84',
 '0',
 '41',
 'NM',
 'NEW MEXICO',
 '6',
 '3547',
 '0',
 '0',
 None,
 '5',
 '0',
 '0',
 '0.1830019',
 '0',
 '9035',
 '35003',
 'county',
 'blockgroup',
 '6929.63']

In [26]:
ej_candidates.loc[ej_candidates['fips_county'] == '36047', 'RAW_D_MINOR':] = ej_query_values

In [27]:
ej_candidates.loc[ej_candidates['fips_county'] == '36047', 'RAW_D_MINOR':]

,RAW_D_MINOR,RAW_D_INCOME,RAW_D_LESSHS,RAW_D_LING,RAW_D_UNDER5,RAW_D_OVER64,RAW_D_UNEMPLOYED,RAW_D_INDEX,RAW_E_LEAD,RAW_E_DIESEL,...,statLayerCount,statLayerZeroPopCount,weightLayerCount,timeSeconds,distance,unit,areaid,areatype,statlevel,inputAreaMiles
0,17%,53%,7%,2%,2%,42%,5%,35%,0.14,0.0102,...,5,0,0,0.1830019,0,9035,35003,county,blockgroup,6929.63
18,17%,53%,7%,2%,2%,42%,5%,35%,0.14,0.0102,...,5,0,0,0.1830019,0,9035,35003,county,blockgroup,6929.63

In [39]:
ej_candidates[ej_query_keys][ej_candidates['fips_county'] == '36047']

,RAW_D_MINOR,RAW_D_INCOME,RAW_D_LESSHS,RAW_D_LING,RAW_D_UNDER5,RAW_D_OVER64,RAW_D_UNEMPLOYED,RAW_D_INDEX,RAW_E_LEAD,RAW_E_DIESEL,...,statLayerCount,statLayerZeroPopCount,weightLayerCount,timeSeconds,distance,unit,areaid,areatype,statlevel,inputAreaMiles
0,17%,53%,7%,2%,2%,42%,5%,35%,0.14,0.0102,...,5,0,0,0.1830019,0,9035,35003,county,blockgroup,6929.63
18,17%,53%,7%,2%,2%,42%,5%,35%,0.14,0.0102,...,5,0,0,0.1830019,0,9035,35003,county,blockgroup,6929.63

In [40]:
fips_list = [fips for fips in ej_candidates['fips_county']]

In [41]:
for fips in fips_list:
    ej_query = requests.get(f'https://ejscreen.epa.gov/mapper/ejscreenRESTbroker.aspx?namestr=Pickens County&geometry=&distance=&unit=9035&areatype=county&areaid={fips}&f=pjson')
    ej_query_values = [value for value in ej_query.json().values()]
    ej_candidates.loc[ej_candidates['fips_county'] == f'{fips}', 'RAW_D_MINOR':] = ej_query_values

There are some percentages values that prevent me from making these numbers floats, so I am going to get rid of the %, I know what is percentage and what is percentile based on the 'EJ_json_dictionary_help.xlsx' file in the folder 'miscellaneous', you can also see a sample of these values from the EJ report screen capture [here](miscellaneous/json_variables_explained.png).

In [43]:
ej_candidates.head()

,latitude (deg),longitude (deg),fips_county,fips_state,name,RAW_D_MINOR,RAW_D_INCOME,RAW_D_LESSHS,RAW_D_LING,RAW_D_UNDER5,...,statLayerCount,statLayerZeroPopCount,weightLayerCount,timeSeconds,distance,unit,areaid,areatype,statlevel,inputAreaMiles
0,40.6943,-73.9249,36047,36,"New York, , New York",64%,37%,17%,14%,7%,...,2156,90,0,0.6476208,0,9035,36047,county,blockgroup,96.85
1,34.1139,-118.4068,06037,06,"Los Angeles, Los Angeles County, California",74%,33%,20%,12%,6%,...,6591,33,0,1.5742393,0,9035,06037,county,blockgroup,4749.41
2,41.8373,-87.6862,17031,17,"Chicago, Cook County, Illinois",58%,30%,12%,7%,6%,...,4002,10,0,1.0323922,0,9035,17031,county,blockgroup,1634.62
3,25.7839,-80.2102,12086,12,"Miami, Miami-Dade County, Florida",86%,39%,18%,25%,6%,...,1843,13,0,0.5279964,0,9035,12086,county,blockgroup,2389.31
4,32.7936,-96.7662,48113,48,"Dallas, Dallas County, Texas",71%,37%,20%,10%,7%,...,1570,20,0,0.4897028,0,9035,48113,county,blockgroup,908.53

In [44]:
ej_candidates = ej_candidates.replace({'%':''}, regex=True)
ej_candidates = ej_candidates.replace('N/A',np.nan)

In [45]:
ej_candidates.loc[:, 'RAW_D_MINOR':'N_P_UST'] = ej_candidates.loc[:, 'RAW_D_MINOR':'N_P_UST'].astype(float)
ej_candidates.loc[:, 'totalPop':'areaid'] = ej_candidates.loc[:, 'totalPop':'areaid'].astype(float)

In [46]:
ej_candidates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Columns: 146 entries, latitude (deg) to inputAreaMiles
dtypes: float64(137), object(9)
memory usage: 178.1+ KB

In [50]:
cwd = os.getcwd()
ej_candidates.to_csv(os.path.join('EJ_files', 'candidate_locations_with_EJ.csv'), index=False)